### ISSUE TITLE
GT.M can not be re-opened

### ISSUE THREAD

**Issue by wpoosanguansit** [dlwicksell/nodem#9] opened 2016-05-15 21:52 UTC
Hi,

I am trying to write save and retrieve functions and I ran into a problem when I test the functions back to back.  One of them will have an error with the returned result from open as GT.M can not be re-opened.  Is this expected?  The next question I have is what is the recommended way to deal with the db close if I have multiple functions dealing with the db?  Right now, I do have db init and open in each function and close the db before exiting the function.  But that still does not seem to work.  Thanks for your help.

**Comment by dlwicksell** [comment] 2016-05-15 23:22
That is the expected behavior. Nodem relies upon the GT.M Call-in interface, which allows a process to open the database one time, and once it has closed its database connection, that process is no longer allowed to open it. So you should only open the connection to GT.M one time in any Node.js process, and you should only close the connection to GT.M one time in any Node.js process, unless you are finished accessing it in that process.

The initialization is what adds Nodem into your Node.js process. And that is something you only need to do one time as well. Initializing Nodem creates the appropriate Nodem object that gives you access to Nodem, using a constructor method which wraps a C++ class which exposes the various Nodem methods. If you require a module more than once, Node.js will only add that module to that process's image one time.

So you only need to require Nodem one time per process, and you only need to initialize Nodem one time per process, and you only need to open the database connection one time per process, and you should only close the connection to the database after you are done talking to GT.M, as you cannot close it and then re-open it in the same process, which is a limitation in the Call-in API of GT.M. Actually you don't even need to close the database connection, because all of its resources will be released whenever a process that is linked with GT.M ends anyway. 

You should therefore not try requiring, initializing, opening, or closing the Nodem interface for each function or method in your Node.js code. I hope that helps.

**Closed** 2016-05-15 23:22 UTC

**Comment by wpoosanguansit** [comment] 2016-05-15 23:54
As this is quite unusual from the normal practice with other db, I hope you do  not mind I rehash it a bit.  So the pattern found in the example is only for short term process.  And for long running processes, we just need to open the connection, init but do not care to close it as it will be garbage collected if and when the process is terminated.  And there is no memory leak as a result of not closing the db.  Is my understanding correct?  Thanks of your help.

**Comment by dlwicksell** [comment] 2016-05-16 00:25
Yes, that is basically correct. When the process is terminated, its resources will be cleaned up and not leaked. That is actually a function of the operating system. When a process dies, its virtual address space is removed and any physical memory mapped to it is freed. In addition, Nodem is using V8 C++ APIs, which themselves allocate memory that is cleaned up by a garbage collector (the JavaScript garbage collector in Node.js). And when I have to allocate dynamic memory on the heap in C code, to work with GT.M, I am careful (I believe) to deallocate it properly.

**Comment by dlwicksell** [comment] 2016-05-16 00:52
For long-running Node.js processes, you should probably close the database in the handler code for stopping the Node process. E.g.

process.on('exit', function() { 
    db.close(); 
});

and

process.on('SIGINT', function() {
    db.close();
});

etc.
Where you can put your own cleanup code right before or after closing the connection to GT.M.

**Comment by wpoosanguansit** [comment] 2016-05-16 01:13
What if the code is in the util file and it doesn't have access to Node or Express process itself?
